In [33]:
#Ex e 90
import pandas as pd
import re

In [3]:
#Read the table into a DataFrame
df = pd.read_csv("euro_winners.csv")
df

,Season,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
0,1955–56,Spain,Real Madrid,4–3,Stade de Reims,France,"Parc des Princes,Paris",38239
1,1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000
2,1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000
3,1958–59,Spain,Real Madrid,2–0,Stade de Reims,France,"Neckarstadion,Stuttgart",72000
4,1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621
...,...,...,...,...,...,...,...,...
58,2013–14,Spain,Real Madrid,4–1,Atlético Madrid,Spain,"Estádio da Luz, Lisbon",60976
59,2014–15,Spain,Barcelona,3–1,Juventus,Italy,"Olympiastadion,Berlin",70442
60,2015–16,Spain,Real Madrid,1–1*[L],Atlético Madrid,Spain,"San Siro,Milan",71942
61,2016–17,Spain,Real Madrid,4–1,Juventus,Italy,"Millennium Stadium,Cardiff",65842
62,2017–18,Spain,Real Madrid,3–1,Liverpool,England,"NSC Olimpiyskiy Stadium,Kiev",61561

In [75]:
#Define the season column as the index
df = pd.read_csv("euro_winners.csv",index_col='Season')
df

,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
Season,,,,,,,
1955–56,Spain,Real Madrid,4–3,Stade de Reims,France,"Parc des Princes,Paris",38239
1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000
1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000
1958–59,Spain,Real Madrid,2–0,Stade de Reims,France,"Neckarstadion,Stuttgart",72000
1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621
...,...,...,...,...,...,...,...
2013–14,Spain,Real Madrid,4–1,Atlético Madrid,Spain,"Estádio da Luz, Lisbon",60976
2014–15,Spain,Barcelona,3–1,Juventus,Italy,"Olympiastadion,Berlin",70442
2015–16,Spain,Real Madrid,1–1*[L],Atlético Madrid,Spain,"San Siro,Milan",71942
2016–17,Spain,Real Madrid,4–1,Juventus,Italy,"Millennium Stadium,Cardiff",65842
2017–18,Spain,Real Madrid,3–1,Liverpool,England,"NSC Olimpiyskiy Stadium,Kiev",61561

In [5]:
#Display the last 5 rows of the table
df.tail(5)

,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
Season,,,,,,,
2013–14,Spain,Real Madrid,4–1,Atlético Madrid,Spain,"Estádio da Luz, Lisbon",60976
2014–15,Spain,Barcelona,3–1,Juventus,Italy,"Olympiastadion,Berlin",70442
2015–16,Spain,Real Madrid,1–1*[L],Atlético Madrid,Spain,"San Siro,Milan",71942
2016–17,Spain,Real Madrid,4–1,Juventus,Italy,"Millennium Stadium,Cardiff",65842
2017–18,Spain,Real Madrid,3–1,Liverpool,England,"NSC Olimpiyskiy Stadium,Kiev",61561

In [16]:
#Display the name of the team who won the championship at season 2000–01 (note
#the dash in the middle, typed by Alt+0150)
df.loc['2000–01','Winners']
df.at['2000–01','Winners']

'Bayern Munich'

In [65]:
#Display the three games with the highest number of attendees
#df[df.Attendance.sort_values(ascending=False).head(3)]

df.sort_values(['Attendance'],ascending=False).head(3)

,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance
Season,,,,,,,
1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621
1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000
1988–89,Italy,Milan,4–0,Steaua Bucureti,Romania,"Camp Nou,Barcelona",97000

In [54]:
d = re.split(r'\-', "1-0") 
d

['1', '0']

In [64]:
d = re.split(r'[0-9]\-\%[0-9]', '1-1*[L]') 
d

['1-1*[L]']

In [79]:
s = '4-1*[L]'
def get_total(s):
    arr = re.split('\D',s)
    return (int(arr[0]) + int(arr[1]))

get_total(s)

5

In [80]:
df['total_s'] = df.Score.apply(get_total)
df.head()

,Nation,Winners,Score,Runners-up,Runner-UpNation,Venue,Attendance,total_s
Season,,,,,,,,
1955–56,Spain,Real Madrid,4–3,Stade de Reims,France,"Parc des Princes,Paris",38239,7
1956–57,Spain,Real Madrid,2–0,Fiorentina,Italy,"Santiago Bernabéu Stadium, Madrid",124000,2
1957–58,Spain,Real Madrid,3–2,Milan,Italy,"Heysel Stadium,Brussels",67000,5
1958–59,Spain,Real Madrid,2–0,Stade de Reims,France,"Neckarstadion,Stuttgart",72000,2
1959–60,Spain,Real Madrid,7–3,Eintracht Frankfurt,Germany,"Hampden Park,Glasgow",127621,10